fund_management_website/fund/urls.py
"""Define the urls for html files"""

from django.urls import path
from django.contrib.auth.views import LogoutView
from fund import views
from fund_management_website import settings

app_name = "fund"

urlpatterns = [
    path("", views.user_login, name = "index"),
    path("register/", views.register, name="register"),
    path("login/", views.user_login, name = "login"),
    path("apply/", views.application, name = "application"),
    path("update_application/<int:id>", views.updateApplication, name = "update_application"),
    path("budget_profile/",views.budgetProfile, name = "budget_profile"),
    path('add_item/', views.addItem,name="add_item"),
    path('add_item_spend/', views.addItemSpendProfile,name="add_item_spend"),
    path('save_item/', views.saveItem,name="save_item"),
    path('save_item_spend/', views.saveItemSpendProfile,name="save_item_spend"),
    path('delete_item/', views.deleteItem,name="delete_item"),
    path("welcome/", views.welcome, name = "welcome"),
    #path("logout/", views.logout, name= "logout")
    path('logout/', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('welcome/', views.info, name="welcome"),
    path('base/', views.base, name="base"),
    path('dashboard/', views.dashboard, name ="dashboard"),
    path('budget_profile/<int:id>', views.budgetProfile, name ="budget_profile"),
    path('spend_profile/<int:id>', views.SpendProfile, name ="spend_profile"),
    path("application_introduction/", views.applicationIntroduction, name = "application_introduction"),
    path("user_profile/<str:username>", views.user_profile, name = "user_profile"),
    path("view_application_status/<int:id>", views.view_application_status, name="view_application_status"),
    path("add_comment/<int:id>", views.add_comment, name= "add_comment"),
    path("review/<int:id>", views.reviewApplication, name="review_application"),
    path("reviews/", views.reviews, name="reviews"),
    path("view_review/<int:id>", views.view_review, name="view_review"),
    path("update_review/<int:id>", views.updateReview, name="update_review"),
    path("upload_evidence/<int:id>", views.upload_evidence, name="upload_evidence"),
]

fund_management_website/fund_management_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fund.urls')),
    path('', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fund_management_website/fund/forms.py
""" Module to define different forms"""
from django import forms
from .models import UserProfile, ApplicationData, User, Comments, Review, BudgetProfile, SpendingItems


class UserForm(forms.ModelForm) :
    """Forms for Users"""
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        """Meta properties of UserForms"""
        model = User
        fields = ('username', 'first_name', 'last_name' ,'email', 'password')

        labels = { 'username' :"Username",
                   'first_name': 'First Name',
                   'last_name':'Last Name',
                   'email' :"Email Address",
                   'password' :'Password', }


class UserProfileForm(forms.ModelForm):
    """Extension form for Users"""
    class Meta:
        """Meta properties of UserProfileForm"""
        model = UserProfile
        fields = ("contact_number",)


class ApplicationForm(forms.ModelForm):
    """Form for Applications"""
    class Meta:
        """Meta properties for Application"""
        model = ApplicationData
        fields = ('organisationName','projectTitle' ,'CH_OSCR_number','projectDesc','userGroupDesc','learningOpp' ,'keyPartnersWork' ,'projImpactClimate' ,'projSupportLocBus',
                  'proContribution', 'application_complete')
        labels = {

            'organisationName' :'Name of the Organisation',
            'projectTitle' :'Project Title',
            'CH_OSCR_number' :'OSCR Number',
            # 'contactName' :"Contact Name",
            # 'contactEmail' :"Contact Email",
            'projectDesc' :"Project Description",
            'userGroupDesc' :"Co-Production (Human)",
            'learningOpp' :"Capacity building (Learning)",
            'keyPartnersWork' :"Partnership working (Systems)",
            'projImpactClimate' :"Climate and Environment",
            'projSupportLocBus' :"Local economic and resilience building",
            'proContribution' :"Social return",
            'application_complete':"Is your application complete?",

        }
        widgets = {

            'organisationName' :forms.TextInput(attrs={ 'class' :'form-control' }),
            'projectTitle' :forms.TextInput(attrs={ 'class' :'form-control' }),
            'CH_OSCR_number' :forms.TextInput(attrs={ 'class' :'form-control' }),
            # 'contactName' :forms.TextInput(attrs={ 'class' :'form-control' }),
            # 'contactEmail' :forms.TextInput(attrs={ 'class' :'form-control' }),
            'projectDesc' :forms.Textarea(attrs={ 'class' :'form-control' }),
            'userGroupDesc' :forms.Textarea(attrs={ 'class' :'form-control' }),
            'learningOpp' :forms.Textarea(attrs={ 'class' :'form-control' }),
            'keyPartnersWork' :forms.Textarea(attrs={ 'class' :'form-control' }),
            'projImpactClimate' :forms.Textarea(attrs={ 'class' :'form-control' }),
            'projSupportLocBus' :forms.Textarea(attrs={ 'class' :'form-control' }),
            'proContribution' :forms.Textarea(attrs={ 'class' :'form-control' }),
            'application_complete':forms.CheckboxInput(attrs={'class':'boolean'}),
        }

class UpdateAppStatus(forms.ModelForm):

    class Meta:
        model = ApplicationData
        fields = ('app_status',)
        labels = {'app_status':'Change application status?'}


class FeedbackForm(forms.ModelForm):

    class Meta:

        model = ApplicationData
        fields = ('feedback',)
        labels = {'feedback': 'Comments and Feedback'}

class CommentForm(forms.ModelForm):
    """Forms for Comments"""

    class Meta:
        """Meta properties of CommentForm"""
        model = Comments
        fields = ('comment', )

        labels = { 'comment' :"Please add your comments for this application", }


class BudgetForm(forms.ModelForm):
    """Forms for Budget Allocation"""
    class Meta:
        """Meta Properties of BudgetForm"""
        model = BudgetProfile
        fields = ('totalBudget',)
        labels = {"totalBudget":"Please state total budget to be allocated to the project",}

class EvidenceForm(forms.ModelForm):
    """Form for uploading Evidence for a spending Item"""
    class Meta:
        """Meta properties of EvidenceForm"""
        model = SpendingItems
        fields = ('evidence',)
        label = {"evidence":"Please upload relevant file for this item",}




class ReviewForm(forms.ModelForm):

    class Meta:

        model = Review

        fields = ('co_production', 'capacity_building', 'partnership_working', 'climate_environment',
                  'local_economic_res_building', 'social_return_acc', 'general_feedback',
                  'review_complete',)

        labels = {

            'co_production' : 'Co-Production (Human)',
            'capacity_building' : 'Capacity building (Learning)',
            'partnership_working' : 'Partnership working (Systems)',
            'climate_environment': 'Climate and Environment',
            'local_economic_res_building' : 'Local economic and resilience building',
            'social_return_acc' : 'Social return and accountability',
            'general_feedback' : 'Comments',
            'review_complete' : 'Is the review ready to be submitted?',

        }


        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)

fund_management_website/fund/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.urls import reverse
from fund.forms import *
from django.views.decorators.csrf import csrf_exempt
from fund.models import *
import json


# Create your views here.

def index(request) :
    return HttpResponse("This is the index page")


def register(request) :
    registered = False
    if request.method == 'POST' :
        user_form = UserForm(request.POST)
        user_profile_form = UserProfileForm(request.POST)
        if user_form.is_valid() and user_profile_form.is_valid() :
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = user_profile_form.save(commit=False)
            profile.user = user

            profile.save()
            registered = True
        else :
            print(user_form.errors)
    else :
        user_form = UserForm()
        user_profile_form = UserProfileForm()
    return render(request,
                  'fund/register.html',
                  { 'user_form' :user_form,
                    'user_profile_form' :user_profile_form,
                    'registered' :registered })


def user_login(request) :
    if request.user.is_authenticated :
        return redirect(reverse('fund:dashboard'))
    if request.method == 'POST' :
        user_form = AuthenticationForm(request=request, data=request.POST)

        if user_form.is_valid() :
            login(request, user_form.get_user())
            return redirect(reverse('fund:dashboard'))
        else :
            print(user_form.errors)

    # else:
    # user_form = AuthenticationForm()
    return render(request, 'fund/login.html')  # {'user_form':user_form})


@login_required
def user_logout(request) :
    logout(request)

def reviewApplication(request, id):
    if not request.user.is_superuser and not request.user.is_staff:
        return redirect("fund:dashboard")
    application = ApplicationData.objects.get(id=id)
    review_form = ReviewForm()
    if request.method == 'POST' :
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.application = application
            review.user = request.user
            #print(review.score())

            review.save()
            review.application.save()

            return redirect("fund:dashboard")
        else:
            print(review_form.errors)
    else:
        return render(request, 'fund/review.html', { 'form' :review_form })

def updateReview(request, id):
    if not request.user.is_superuser and request.user.is_staff:
        return redirect("fund:dashboard")
    review = Review.objects.get(id=id)
    review_form = ReviewForm(instance= review)
    if request.method == 'POST':
        review_form = ReviewForm(request.POST, instance = review)
        if review_form.is_valid:
            review_form.save()
            return redirect("fund:dashboard")
        else:
            print(review_form.errors)
    return render(request, 'fund/review.html', context = {'title_text':"Update your review", 'form':review_form, 'form_text':"Update your review"})



def application(request) :
    user = request.user
    print(user)
    application_form = ApplicationForm()
    budget_form = BudgetForm()
    if request.method == 'POST' :
        application_form = ApplicationForm(request.POST)
        budget_form = BudgetForm(request.POST)
        if application_form.is_valid() :
            print("form is valid")
            application = application_form.save(commit=False)
            application.user = user
            budget= budget_form.save(commit=False)
            application.associated_budgetProfile = budget
            # budget.associated_application = application
            print(application.user)
            budget.save()
            application.save()

            return redirect('fund:dashboard')
        else :
            print(application_form.errors)
    else :

        return render(request, 'fund/application.html', { 'form' :application_form, 'form1':budget_form })


# id is the application id
def updateApplication(request, id) :
    applicationObj = ApplicationData.objects.get(id=id)
    application_form = ApplicationForm(instance=applicationObj)
    budgetInstance = applicationObj.associated_budgetProfile
    #budgetObj = BudgetProfile.objects.get(associated_application = applicationObj)
    budget_form = BudgetForm(instance=budgetInstance)
    if request.method == 'POST' :
        application_form = ApplicationForm(request.POST, instance=applicationObj)
        budget_form = BudgetForm(request.POST, instance=budgetInstance)
        if application_form.is_valid() :
            print("form is valid")
            application_form.save()
            budget_form.save()
            return redirect('fund:dashboard')
        else :
            print(application_form.errors)
    else :
        return render(request, 'fund/application.html', { 'form' :application_form , 'form1':budget_form})


def budgetProfile(request, id) :
    application= ApplicationData.objects.get(id =id)
    bP = application.associated_budgetProfile
    #items = BudgetItems.objects.get(associated_budget_profile = bP)
    try:
        items = BudgetItems.objects.filter(associated_budget_profile = bP)

    except:
        items = None
        pass
    #subItems = BudgetItems.objects.get

    return render(request, "fund/budgetProfile.html", { "items" :items, "app_id":application.id, "application":application })


def SpendProfile(request, id) :
    app = ApplicationData.objects.get(id =id)
    sp = SpendingProfile.objects.get(associated_application =app)
    items = SpendingItems.objects.filter(associated_spending_profile =sp)
    #if not items: print("its not here")
    #for i in items:
        #print(i)
    # items = SpendingItems.objects.get(associated_application =app)
    # spendObj = SpendingItems.objects.get(id=id)
    # item =  SpendingItems(request.POST, instance=spendObj)
    # item.save()
    # headings = BudgetItems.objects.all()
    return render(request, "fund/SpendProfile.html", {'items':items, 'app_id':app.id})


@csrf_exempt
def addItem(request) :
    app_id =request.POST.get("app_id")
    print(app_id)
    bP = ApplicationData.objects.get(id = int(app_id)).associated_budgetProfile
    #sp = SpendingProfile.objects.get(associated_application =app_id)
    ID = request.POST.get("ID")
    heading = request.POST.get("heading1")
    item_name = request.POST.get("item_name")
    description = request.POST.get("description")
    budget_allocation = request.POST.get("budget_allocation")

    try :
        # heading = SubBudgetProfile(heading=heading)
        # heading.save()
        item = BudgetItems(ID=ID, associated_budget_profile=bP,heading=heading, item_name=item_name, description=description,
                           budget_allocation=budget_allocation)
        item.save()
        try:
            spend_items = SpendingItems(ID=ID, associated_spending_profile=sp,heading=heading, item_name=item_name, description=description,
                                        budget_allocation=budget_allocation)
            spend_items.save()

        except:
            print("There is no spend items yet")
            pass
        item_data = { "app_id" :item.ID, "error" :False, "errorMessage" :"Item Added Successfully" }
        return JsonResponse(item_data, safe=False)
    except :
        item_data = { "error" :True, "errorMessage" :"Failed to add item" }
        return JsonResponse(item_data, safe=False)


@csrf_exempt
def addItemSpendProfile(request) :
    app_id = request.POST.get("app_id")
    sp = SpendingProfile.objects.get(associated_application = ApplicationData.objects.get(id =app_id))
    heading = request.POST.get("heading")
    ID = request.POST.get("ID")
    item_name = request.POST.get("item_name")
    description = request.POST.get("description")
    money_spent = request.POST.get("money_spent")
    bP_budget_allocation = request.POST.get("bP_budget_allocation")

    try :

        spend_items = SpendingItems(ID=ID, heading=heading, item_name=item_name, description=description,
                                    money_spent=money_spent,budget_allocation=bP_budget_allocation, associated_spending_profile =sp)
        spend_items.save()
        item_data = { "heading" :spend_items.ID, "error" :False, "errorMessage" :"Item Added Successfully" }
        return JsonResponse(item_data, safe=False)
    except :
        item_data = { "error" :True, "errorMessage" :"Failed to add item" }
        return JsonResponse(item_data, safe=False)


@csrf_exempt
def saveItem(request) :
    data = request.POST.get("data")
    dict_data = json.loads(data)
    try :
        for dic_single in dict_data :
            #heading = SubBudgetProfile(heading=dic_single['heading'])
            #heading.save()
            # item2 = BudgetItems(heading=heading.heading)
            # item2.save()
            # item_heading = SubBudgetProfile.objects.get(heading=dic_single['heading'])
            item = BudgetItems.objects.get(ID=dic_single['ID'])
            item.heading=dic_single['heading']
            item.item_name = dic_single['item_name']
            item.description = dic_single['description']
            item.budget_allocation = dic_single['budget_allocation']
            item.save()
        item_data = { "error" :False, "errorMessage" :"Items Updated Successfully" }
        return JsonResponse(item_data, safe=False)
    except :
        item_data = { "error" :True, "errorMessage" :"Failed to Update Data" }
        return JsonResponse(item_data, safe=False)


@csrf_exempt

fund_management_website/templates/fund/add_to_db_evidence.html
{% extends 'fund/base.html' %}
{% load static %}

{%block title_block %}
   {{title_text}}
{% endblock %}

{% block body_block %}

    <div class = "container-fluid pb-3 col-8 border rounded-1 px-5 p-5">
        <h1 class="text-center"> {{form_text}} </h1>
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <br>
            {{form.as_p}}
            <br>
            <input type="submit" value="Submit" class="btn btn-primary" onclick="check_empty();">
        </form>
    </div>
{% endblock %}

fund_management_website/templates/fund/dashboard.html
{% extends 'fund/base.html' %}
{% load static %}

{%block title_block %}
    Dashboard
{% endblock %}

{% block body_block %}

<main role="main" class="inner cover">
    <div class="container-fluid">
        <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">

            <h1 class="cover-heading text-center">Welcome to your {% if user.is_superuser and not user.is_staff %}LAG member{% endif %}{% if user.is_superuser and user.is_staff %}
              Staff{% endif %} dashboard</h1>
              <p class="lead text-center">This is your current dashboard,{% if not user.is_superuser and not user.is_staff %} you can see all your applications that you have submitted
                and/or have in progress.{% elif user.is_superuser and not user.is_staff%}<br> you can see all the registered users and all submitted applications waiting to be reviewed.
                {% else %}<br> you can see all the registered users and access applications and reviews.{% endif %}</p>
        </div>
    </div>
    <hr>
    <div class="container">
        <p class="h3 text-center">Profile</p>
        <div class="row">
            <div class="col-4">
                <img src="{% static 'svg/person.svg'%}" class="img-fluid float-left" height=100 width=100 alt="Person Icon"/>
            </div>
            <div class="col-8">
                <table class="table table-borderless">
                    <thead>
                    </thead>
                    <tbody>
                    <tr>
                            <td>Username </td>
                            <td>{{username}}</td>
                        </tr>
                        <tr>
                            <td>Name: </td>
                            <td> {{full_name}}</td>
                        </tr>
                        <tr>
                            <td>Email: </td>
                            <td><a href="mailto:{{email}}">{{email}}</a></td>
                        </tr>
                    {% if contact %}
                        <tr>
                            <td>Contact: </td>
                            <td>{{contact}}</td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <hr>

    {% if not user.is_superuser and not user.is_staff %}
    <div class="container">
        <p class="h3 text-center">Application</p>
        <p class="h5 text-muted text-center">Want to apply for a new application?   <a class="mt-3 mb-3 btn btn-secondary" href="{% url 'fund:application_introduction' %}">Apply Here</a> </p>

    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <img src="{%static 'svg/table.svg' %}" alt="Table Icon" width=20 height=20 />
                    Incomplete Applications
                </div>
                <div class="card-body">
                    <table class="dataTable table table-striped table-hover tableresponsive">
                        <thead>
                            <tr>
                                <th>Application ID</th>
                                <th>Application Title</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for application in incomplete_applications %}
                        <tr>
                            <td>{{application.id}}</td>
                            {% if application.projectTitle %}
                            <td>{{application.projectTitle}}</td>
                            {% else %}
                            <td>N/A</td>
                            {% endif %}
                            <td><a href="{%url 'fund:update_application' application.id %}"> Update</a></td>
                            <td><a href="{% url 'fund:budget_profile' application.id %}">Edit Budget Profile</a></td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <img src="{%static 'svg/table.svg' %}" alt="Table Icon" width=20 height=20/>
                    Completed Application
                </div>
                <div class="card-body">
                    <table id="dataTable" class="dataTable table table-striped table-hover tableresponsive">
                        <thead>
                            <tr>
                                <th>Application ID</th>
                                <th>Application Title</th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for application in completed_applications %}
                        <tr>
                            <td>{{application.id}}</td>
                            <td>{{application.projectTitle}}</td>
                            <td><a href="{%url 'fund:update_application' application.id %}"> Update</a></td>
                            <td><a href="{% url 'fund:view_application_status' application.id %}"> View Status </a></td>
                            <td><a href="{% url 'fund:budget_profile' application.id %}">Budget Profile</a></td>
                            {% if application.app_status == "Accepted" %}
                            <td><a href="{% url 'fund:spend_profile' application.id%}">Spend Profile</a></td>
                            {% else %}
                            <td></td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>
    {% else %}
     <div class="container">

        <div class="row">
            <div class="col-6">
                <p class="h3 text-center">
                        {% if request.user.is_superuser and request.user.is_staff %}
                            Users
                        {% else %}
                            Applicants
                        {% endif %}</p>
                <div class="card">
                    <div class="card-header">
                        <img src="{%static 'svg/table.svg' %}" alt="Table Icon" width=20 height=20 />
                        {% if request.user.is_superuser and request.user.is_staff %}
                            Users
                        {% else %}
                            Applicants
                        {% endif %}
                    </div>

                    <div class="card-body">
                        <table class="dataTable table table-striped table-hover tableresponsive">
                            <thead>
                                <tr>
                                    <th>Full name</th>
                                    <th>Username</th>
                                    <th>User type</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for user in user_list %}
                                {% if not user.is_staff or not user.is_superuser%}
                            <tr>

                                {% if user.get_full_name %}
                                <td>{{user.get_full_name}}</td>
                                {% else %}
                                <td>N\A</td>
                                {% endif %}
                                 <td><a href="{% url 'fund:user_profile' user.username %}"</a>{{user.username}}</td>
                                {% if user.is_superuser and not user.is_staff %}
                                <td>LAG Member</td>
                                {% else %}
                                <td>Applicant</td>
                                {% endif %}
                            </tr>
                            {% endif %}
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="col-6">
                <p class="h3 text-center">Applications Summary</p>
                <div class="card">
                    <div class="card-header">
                        <img src="{%static 'svg/table.svg' %}" alt="Table Icon" width=20 height=20 />
                        Applications
                    </div>

                    <div class="card-body">
                        <table class="dataTable table table-striped table-hover tableresponsive">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Project Name</th>
                                    <th>Date Submitted</th>
                                    <th>View status</th>
                                    <th>Review</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for app in completed_applications %}
                            <tr>
                                <td>{{app.id}}</td>
                                <td>{{app.projectTitle}}</td>
                                <td>{{app.date_of_application}}</td>
                                <td><a href="{% url 'fund:view_application_status' app.id %}"> View Status </a></td>
                                {% if user.is_superuser and not user.is_staff %}
                                <td><a href="{% url 'fund:review_application' app.id %}">Review</a></td>
                                {% else %}
                                <td><a href="{% url 'fund:reviews' %}">Reviews</a></td>
                                {% endif %}

                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</main>

{% endblock %}

fund_management_website/templates/fund/welcome.html
{% extends 'fund/base.html' %}
{% load static %}
{% load bootstrap5 %}

<!DOCTYPE html>
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <title>
        {% block title_block %}
            Welcome to Fund Management Portal
        {% endblock %}
    </title>
</head>

{% block body_block %}
<body class="text-center">
<div class="container-fluid mt-5">

    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
        <!-- <div style="text-align: left;">
             <header class="masthead mb-auto">
                <a class = "btn btn-danger" href="{% url 'fund:logout' %}">Logout</a>
            </header> -->
        </div> -->
        <main role="main" class="inner cover">
            <h1 class="cover-heading">Welcome to the funding portal</h1>
            <p class="lead">This is your current dashboard, you can see all your application that you have submitted and/or have in progress.
            </p>
            <p class="lead">
                Apply for funding here.
                <br> <a class="mt-3 mb-3 btn btn-primary" href="{%url 'fund:application' %}">Application Form</a> </br>
                <br> <a class="mt-3 mb-3 btn btn-primary" href="{%url 'fund:update_application' 1 %}">Update Application</a> </br>
                <br> <a class="mt-3 mb-3 btn btn-primary" href="{%url 'fund:budget_profile' %}">Budget Profile</a> </br>
            </p>
        </main>

    </div>
</div>
</body>
{% endblock body_block %}
</html>